---
version: '3.3'
services:
  kafka1:
    image: exampleplatform/kafka:latest
    volumes:
      - type: volume
        source: k1-logs
        target: /tmp/kafka-logs
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    ports:
      - target: 9093
        published: 9093
    networks:
      - kafka-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.kafka==1
    command: >
        /kafka/bin/kafka-server-start.sh /kafka/config/server.properties
        --override zookeeper.connect=zookeeper:2181
        --override listeners=INT://:9092,EXT://0.0.0.0:9093
        --override listener.security.protocol.map=INT:PLAINTEXT,EXT:PLAINTEXT
        --override inter.broker.listener.name=INT
        --override advertised.listeners=INT://:9092,EXT://10.0.0.12:9093
        --override broker.id=1

  kafka2:
    image: exampleplatform/kafka:latest
    volumes:
      - type: volume
        source: k2-logs
        target: /tmp/kafka-logs
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    ports:
      - target: 9094
        published: 9094
    networks:
      - kafka-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.kafka==2
    command: >
        /kafka/bin/kafka-server-start.sh /kafka/config/server.properties
        --override zookeeper.connect=zookeeper:2181
        --override listeners=INT://:9092,EXT://0.0.0.0:9094
        --override listener.security.protocol.map=INT:PLAINTEXT,EXT:PLAINTEXT
        --override inter.broker.listener.name=INT
        --override advertised.listeners=INT://:9092,EXT://10.0.0.13:9094
        --override broker.id=2

  kafka3:
    image: exampleplatform/kafka:latest
    volumes:
      - type: volume
        source: k3-logs
        target: /tmp/kafka-logs
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    ports:
      - target: 9095
        published: 9095
    networks:
      - kafka-net
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.kafka==3
    command: >
        /kafka/bin/kafka-server-start.sh /kafka/config/server.properties
        --override zookeeper.connect=zookeeper:2181
        --override listeners=INT://:9092,EXT://0.0.0.0:9095
        --override listener.security.protocol.map=INT:PLAINTEXT,EXT:PLAINTEXT
        --override inter.broker.listener.name=INT
        --override advertised.listeners=INT://:9092,EXT://10.0.0.14:9095
        --override broker.id=3

networks:
  kafka-net:
    driver: overlay
volumes:
  k1-logs:
  k2-logs:
  k3-logs:
